package com.all580.role.dao;

import java.util.List;
import java.util.Map;

public interface FuncGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_group
     *
     * @mbggenerated Wed Jun 28 17:40:48 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_group
     *
     * @mbggenerated Wed Jun 28 17:40:48 CST 2017
     */
    int insert(Map record);




    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_group
     *
     * @mbggenerated Wed Jun 28 17:40:48 CST 2017
     */
    Map selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_group
     *
     * @mbggenerated Wed Jun 28 17:40:48 CST 2017
     */
    int updateByPrimaryKeySelective(Map record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_func_group
     *
     * @mbggenerated Wed Jun 28 17:40:48 CST 2017
     */
    int updateByPrimaryKey(Map record);

    int insertSelective(Map map);
    List<Map<String,Object>> selectFuncGroupList();

}