package com.all580.order.entity;

import java.io.Serializable;
import java.util.Date;

public class ClearanceWashedSerial implements Serializable {
    /**
     * 主键
     * 所属表字段为 t_clearance_washed_serial.id
     */
    private Integer id;

    /**
     * 第三方冲正流水
     * 所属表字段为 t_clearance_washed_serial.serial_no
     */
    private String serial_no;

    /**
     * 核销流水
     * 所属表字段为 t_clearance_washed_serial.clearance_serial_no
     */
    private String clearance_serial_no;

    /**
     * 数量
     * 所属表字段为 t_clearance_washed_serial.quantity
     */
    private Integer quantity;

    /**
     * 哪一天的票
     * 所属表字段为 t_clearance_washed_serial.day
     */
    private Date day;

    /**
     * 反核销供应平台商应退回金额
     * 所属表字段为 t_clearance_washed_serial.supplier_money
     */
    private Integer supplier_money;

    /**
     * 通道费率
     * 所属表字段为 t_clearance_washed_serial.channel_fee
     */
    private Integer channel_fee;

    /**
     * 冲正时间
     * 所属表字段为 t_clearance_washed_serial.clearance_washed_time
     */
    private Date clearance_washed_time;

    /**
     * 创建时间
     * 所属表字段为 t_clearance_washed_serial.create_time
     */
    private Date create_time;

    /**
     * 所属表字段为 t_clearance_washed_serial.update_time
     */
    private String update_time;

    /**
     * 是否已经分账
     * 所属表字段为 t_clearance_washed_serial.split
     */
    private Boolean split;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clearance_washed_serial.id
     *
     * @return the value of t_clearance_washed_serial.id
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clearance_washed_serial.id
     *
     * @param id the value for t_clearance_washed_serial.id
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clearance_washed_serial.serial_no
     *
     * @return the value of t_clearance_washed_serial.serial_no
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public String getSerial_no() {
        return serial_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clearance_washed_serial.serial_no
     *
     * @param serial_no the value for t_clearance_washed_serial.serial_no
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public void setSerial_no(String serial_no) {
        this.serial_no = serial_no == null ? null : serial_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clearance_washed_serial.clearance_serial_no
     *
     * @return the value of t_clearance_washed_serial.clearance_serial_no
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public String getClearance_serial_no() {
        return clearance_serial_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clearance_washed_serial.clearance_serial_no
     *
     * @param clearance_serial_no the value for t_clearance_washed_serial.clearance_serial_no
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public void setClearance_serial_no(String clearance_serial_no) {
        this.clearance_serial_no = clearance_serial_no == null ? null : clearance_serial_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clearance_washed_serial.quantity
     *
     * @return the value of t_clearance_washed_serial.quantity
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clearance_washed_serial.quantity
     *
     * @param quantity the value for t_clearance_washed_serial.quantity
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clearance_washed_serial.day
     *
     * @return the value of t_clearance_washed_serial.day
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clearance_washed_serial.day
     *
     * @param day the value for t_clearance_washed_serial.day
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clearance_washed_serial.supplier_money
     *
     * @return the value of t_clearance_washed_serial.supplier_money
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public Integer getSupplier_money() {
        return supplier_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clearance_washed_serial.supplier_money
     *
     * @param supplier_money the value for t_clearance_washed_serial.supplier_money
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public void setSupplier_money(Integer supplier_money) {
        this.supplier_money = supplier_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clearance_washed_serial.channel_fee
     *
     * @return the value of t_clearance_washed_serial.channel_fee
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public Integer getChannel_fee() {
        return channel_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clearance_washed_serial.channel_fee
     *
     * @param channel_fee the value for t_clearance_washed_serial.channel_fee
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public void setChannel_fee(Integer channel_fee) {
        this.channel_fee = channel_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clearance_washed_serial.clearance_washed_time
     *
     * @return the value of t_clearance_washed_serial.clearance_washed_time
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public Date getClearance_washed_time() {
        return clearance_washed_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clearance_washed_serial.clearance_washed_time
     *
     * @param clearance_washed_time the value for t_clearance_washed_serial.clearance_washed_time
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public void setClearance_washed_time(Date clearance_washed_time) {
        this.clearance_washed_time = clearance_washed_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clearance_washed_serial.create_time
     *
     * @return the value of t_clearance_washed_serial.create_time
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clearance_washed_serial.create_time
     *
     * @param create_time the value for t_clearance_washed_serial.create_time
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clearance_washed_serial.update_time
     *
     * @return the value of t_clearance_washed_serial.update_time
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public String getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clearance_washed_serial.update_time
     *
     * @param update_time the value for t_clearance_washed_serial.update_time
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public void setUpdate_time(String update_time) {
        this.update_time = update_time == null ? null : update_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clearance_washed_serial.split
     *
     * @return the value of t_clearance_washed_serial.split
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public Boolean getSplit() {
        return split;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clearance_washed_serial.split
     *
     * @param split the value for t_clearance_washed_serial.split
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    public void setSplit(Boolean split) {
        this.split = split;
    }
}