package com.all580.order.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class GroupConsume implements Serializable {
    /**
     * 所属表字段为 t_group_consume.id
     */
    private Integer id;

    /**
     * 验票流水
     * 所属表字段为 t_group_consume.validate_sn
     */
    private String validate_sn;

    /**
     * 子订单ID
     * 所属表字段为 t_group_consume.order_item_id
     */
    private Integer order_item_id;

    /**
     * 团队ID
     * 所属表字段为 t_group_consume.group_id
     */
    private Integer group_id;

    /**
     * 核销流水ID
     * 所属表字段为 t_group_consume.clearance_serial_id
     */
    private Integer clearance_serial_id;

    /**
     * 核销证件
     * 所属表字段为 t_group_consume.sid
     */
    private String sid;

    /**
     * 所属表字段为 t_group_consume.create_time
     */
    private Date create_time;

    /**
     * 所属表字段为 t_group_consume.update_time
     */
    private String update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_group_consume
     *
     * @mbggenerated Thu Dec 08 17:14:02 CST 2016
     */
    private static final long serialVersionUID = 1L;

}