package com.all580.order.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class MaSendResponse implements Serializable {
    /**
     * 所属表字段为 t_ma_send_response.id
     */
    private Integer id;

    /**
     * 游客ID
     * 所属表字段为 t_ma_send_response.visitor_id
     */
    private Integer visitor_id;

    /**
     * 子订单ID
     * 所属表字段为 t_ma_send_response.order_item_id
     */
    private Integer order_item_id;

    /**
     * 凭证订单ID
     * 所属表字段为 t_ma_send_response.ma_order_id
     */
    private String ma_order_id;

    /**
     * 发码公司中的产品ID
     * 所属表字段为 t_ma_send_response.ma_product_id
     */
    private String ma_product_id;

    /**
     * 凭证ID
     * 所属表字段为 t_ma_send_response.ep_ma_id
     */
    private Integer ep_ma_id;

    /**
     * 二维码图像链接
     * 所属表字段为 t_ma_send_response.image_url
     */
    private String image_url;

    /**
     * 电子凭证号
     * 所属表字段为 t_ma_send_response.voucher_value
     */
    private String voucher_value;

    /**
     * 身份证
     * 所属表字段为 t_ma_send_response.sid
     */
    private String sid;

    /**
     * 手机号码
     * 所属表字段为 t_ma_send_response.phone
     */
    private String phone;

    /**
     * 所属表字段为 t_ma_send_response.create_time
     */
    private Date create_time;

    /**
     * 所属表字段为 t_ma_send_response.update_time
     */
    private String update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ma_send_response
     *
     * @mbggenerated Fri Nov 25 14:51:24 CST 2016
     */
    private static final long serialVersionUID = 1L;

}