package com.all580.order.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class OrderItemDetail implements Serializable {
    /**
     * 所属表字段为 t_order_item_detail.id
     */
    private Integer id;

    /**
     * 子订单id
     * 所属表字段为 t_order_item_detail.order_item_id
     */
    private Integer orderItemId;

    /**
     * 日期
     * 所属表字段为 t_order_item_detail.day
     */
    private Date day;

    /**
     * 数量
     * 所属表字段为 t_order_item_detail.quantity
     */
    private Integer quantity;

    /**
     * 核销数量
     * 所属表字段为 t_order_item_detail.used_quantity
     */
    private Integer usedQuantity;

    /**
     * 退订数量
     * 所属表字段为 t_order_item_detail.refund_quantity
     */
    private Integer refundQuantity;

    /**
     * 销售侧退款规则
     * 所属表字段为 t_order_item_detail.cust_refund_rule
     */
    private String custRefundRule;

    /**
     * 供应侧退款规则
     * 所属表字段为 t_order_item_detail.saler_refund_rule
     */
    private String salerRefundRule;

    /**
     * 验票规则
     * 所属表字段为 t_order_item_detail.clearance_rule
     */
    private String clearanceRule;

    /**
     * 是否超买
     * 所属表字段为 t_order_item_detail.oversell
     */
    private Boolean oversell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_item_detail
     *
     * @mbggenerated Wed Oct 12 11:43:48 CST 2016
     */
    private static final long serialVersionUID = 1L;

}