package com.all580.order.entity;

import java.io.Serializable;
import java.util.Date;

public class OrderItem implements Serializable {
    /**
     * 所属表字段为 t_order_item.id
     */
    private Integer id;

    /**
     * 所属表字段为 t_order_item.number
     */
    private Long number;

    /**
     * 主订单id
     * 所属表字段为 t_order_item.order_id
     */
    private Integer order_id;

    /**
     * 子产品CODE
     * 所属表字段为 t_order_item.pro_sub_number
     */
    private Long pro_sub_number;

    /**
     * 子产品id
     * 所属表字段为 t_order_item.pro_sub_id
     */
    private Integer pro_sub_id;

    /**
     * 主产品名
     * 所属表字段为 t_order_item.pro_name
     */
    private String pro_name;

    /**
     * 子产品名
     * 所属表字段为 t_order_item.pro_sub_name
     */
    private String pro_sub_name;

    /**
     * 产品类型
     * 所属表字段为 t_order_item.pro_type
     */
    private Integer pro_type;

    /**
     * 开始时间
     * 所属表字段为 t_order_item.start
     */
    private Date start;

    /**
     * 结束时间
     * 所属表字段为 t_order_item.end
     */
    private Date end;

    /**
     * 天数
     * 所属表字段为 t_order_item.days
     */
    private Integer days;

    /**
     * 数量
     * 所属表字段为 t_order_item.quantity
     */
    private Integer quantity;

    /**
     * 已用总张数
     * 所属表字段为 t_order_item.used_quantity
     */
    private Integer used_quantity;

    /**
     * 已退订总张数
     * 所属表字段为 t_order_item.refund_quantity
     */
    private Integer refund_quantity;

    /**
     * 1-待审核
2-审核通过
3-未出票
4-出票失败
5-出票中
6-已出票
7-已取消
     * 所属表字段为 t_order_item.status
     */
    private Integer status;

    /**
     * 出票调用记录id
     * 所属表字段为 t_order_item.send_ma_log_rec_id
     */
    private Integer send_ma_log_rec_id;

    /**
     * 出票时间
     * 所属表字段为 t_order_item.send_ma_time
     */
    private Date send_ma_time;

    /**
     * 团队id 0表示散客
     * 所属表字段为 t_order_item.group_id
     */
    private Integer group_id;

    /**
     * 1-预付
2-平台代收预付
3-到付
     * 所属表字段为 t_order_item.payment_flag
     */
    private Integer payment_flag;

    /**
     * 销售金额
     * 所属表字段为 t_order_item.sale_amount
     */
    private Integer sale_amount;

    /**
     * 票据类型
     * 所属表字段为 t_order_item.ticket_type
     */
    private Integer ticket_type;

    /**
     * 最底层供应商ID
     * 所属表字段为 t_order_item.supplier_ep_id
     */
    private Integer supplier_ep_id;

    /**
     * 供应商平台商ID
     * 所属表字段为 t_order_item.supplier_core_ep_id
     */
    private Integer supplier_core_ep_id;

    /**
     * 供应商短信通知手机号码
     * 所属表字段为 t_order_item.supplier_phone
     */
    private String supplier_phone;

    /**
     * 最低使用张数限制（团队票）
     * 所属表字段为 t_order_item.low_quantity
     */
    private Integer low_quantity;

    /**
     * 凭证商户关联ID t_ma.id
     * 所属表字段为 t_order_item.ep_ma_id
     */
    private Integer ep_ma_id;

    /**
     * 审核用户ID
     * 所属表字段为 t_order_item.audit_user_id
     */
    private Integer audit_user_id;

    /**
     * 审核用户名称
     * 所属表字段为 t_order_item.audit_user_name
     */
    private String audit_user_name;

    /**
     * 所属表字段为 t_order_item.update_time
     */
    private String update_time;

    /**
     * 审核通过时间
     * 所属表字段为 t_order_item.audit_time
     */
    private Date audit_time;

    /**
     * 退款审核
     * 所属表字段为 t_order_item.refund_money_audit
     */
    private Integer refund_money_audit;

    /**
     * 退订审核
     * 所属表字段为 t_order_item.refund_audit
     */
    private Integer refund_audit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_item
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.id
     *
     * @return the value of t_order_item.id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.id
     *
     * @param id the value for t_order_item.id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.number
     *
     * @return the value of t_order_item.number
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Long getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.number
     *
     * @param number the value for t_order_item.number
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setNumber(Long number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.order_id
     *
     * @return the value of t_order_item.order_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.order_id
     *
     * @param order_id the value for t_order_item.order_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.pro_sub_number
     *
     * @return the value of t_order_item.pro_sub_number
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Long getPro_sub_number() {
        return pro_sub_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.pro_sub_number
     *
     * @param pro_sub_number the value for t_order_item.pro_sub_number
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setPro_sub_number(Long pro_sub_number) {
        this.pro_sub_number = pro_sub_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.pro_sub_id
     *
     * @return the value of t_order_item.pro_sub_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getPro_sub_id() {
        return pro_sub_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.pro_sub_id
     *
     * @param pro_sub_id the value for t_order_item.pro_sub_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setPro_sub_id(Integer pro_sub_id) {
        this.pro_sub_id = pro_sub_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.pro_name
     *
     * @return the value of t_order_item.pro_name
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public String getPro_name() {
        return pro_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.pro_name
     *
     * @param pro_name the value for t_order_item.pro_name
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setPro_name(String pro_name) {
        this.pro_name = pro_name == null ? null : pro_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.pro_sub_name
     *
     * @return the value of t_order_item.pro_sub_name
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public String getPro_sub_name() {
        return pro_sub_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.pro_sub_name
     *
     * @param pro_sub_name the value for t_order_item.pro_sub_name
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setPro_sub_name(String pro_sub_name) {
        this.pro_sub_name = pro_sub_name == null ? null : pro_sub_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.pro_type
     *
     * @return the value of t_order_item.pro_type
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getPro_type() {
        return pro_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.pro_type
     *
     * @param pro_type the value for t_order_item.pro_type
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setPro_type(Integer pro_type) {
        this.pro_type = pro_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.start
     *
     * @return the value of t_order_item.start
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.start
     *
     * @param start the value for t_order_item.start
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.end
     *
     * @return the value of t_order_item.end
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.end
     *
     * @param end the value for t_order_item.end
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setEnd(Date end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.days
     *
     * @return the value of t_order_item.days
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.days
     *
     * @param days the value for t_order_item.days
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.quantity
     *
     * @return the value of t_order_item.quantity
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.quantity
     *
     * @param quantity the value for t_order_item.quantity
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.used_quantity
     *
     * @return the value of t_order_item.used_quantity
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getUsed_quantity() {
        return used_quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.used_quantity
     *
     * @param used_quantity the value for t_order_item.used_quantity
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setUsed_quantity(Integer used_quantity) {
        this.used_quantity = used_quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.refund_quantity
     *
     * @return the value of t_order_item.refund_quantity
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getRefund_quantity() {
        return refund_quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.refund_quantity
     *
     * @param refund_quantity the value for t_order_item.refund_quantity
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setRefund_quantity(Integer refund_quantity) {
        this.refund_quantity = refund_quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.status
     *
     * @return the value of t_order_item.status
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.status
     *
     * @param status the value for t_order_item.status
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.send_ma_log_rec_id
     *
     * @return the value of t_order_item.send_ma_log_rec_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getSend_ma_log_rec_id() {
        return send_ma_log_rec_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.send_ma_log_rec_id
     *
     * @param send_ma_log_rec_id the value for t_order_item.send_ma_log_rec_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setSend_ma_log_rec_id(Integer send_ma_log_rec_id) {
        this.send_ma_log_rec_id = send_ma_log_rec_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.send_ma_time
     *
     * @return the value of t_order_item.send_ma_time
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Date getSend_ma_time() {
        return send_ma_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.send_ma_time
     *
     * @param send_ma_time the value for t_order_item.send_ma_time
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setSend_ma_time(Date send_ma_time) {
        this.send_ma_time = send_ma_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.group_id
     *
     * @return the value of t_order_item.group_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getGroup_id() {
        return group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.group_id
     *
     * @param group_id the value for t_order_item.group_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setGroup_id(Integer group_id) {
        this.group_id = group_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.payment_flag
     *
     * @return the value of t_order_item.payment_flag
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getPayment_flag() {
        return payment_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.payment_flag
     *
     * @param payment_flag the value for t_order_item.payment_flag
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setPayment_flag(Integer payment_flag) {
        this.payment_flag = payment_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.sale_amount
     *
     * @return the value of t_order_item.sale_amount
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getSale_amount() {
        return sale_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.sale_amount
     *
     * @param sale_amount the value for t_order_item.sale_amount
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setSale_amount(Integer sale_amount) {
        this.sale_amount = sale_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.ticket_type
     *
     * @return the value of t_order_item.ticket_type
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getTicket_type() {
        return ticket_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.ticket_type
     *
     * @param ticket_type the value for t_order_item.ticket_type
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setTicket_type(Integer ticket_type) {
        this.ticket_type = ticket_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.supplier_ep_id
     *
     * @return the value of t_order_item.supplier_ep_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getSupplier_ep_id() {
        return supplier_ep_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.supplier_ep_id
     *
     * @param supplier_ep_id the value for t_order_item.supplier_ep_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setSupplier_ep_id(Integer supplier_ep_id) {
        this.supplier_ep_id = supplier_ep_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.supplier_core_ep_id
     *
     * @return the value of t_order_item.supplier_core_ep_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getSupplier_core_ep_id() {
        return supplier_core_ep_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.supplier_core_ep_id
     *
     * @param supplier_core_ep_id the value for t_order_item.supplier_core_ep_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setSupplier_core_ep_id(Integer supplier_core_ep_id) {
        this.supplier_core_ep_id = supplier_core_ep_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.supplier_phone
     *
     * @return the value of t_order_item.supplier_phone
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public String getSupplier_phone() {
        return supplier_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.supplier_phone
     *
     * @param supplier_phone the value for t_order_item.supplier_phone
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setSupplier_phone(String supplier_phone) {
        this.supplier_phone = supplier_phone == null ? null : supplier_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.low_quantity
     *
     * @return the value of t_order_item.low_quantity
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getLow_quantity() {
        return low_quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.low_quantity
     *
     * @param low_quantity the value for t_order_item.low_quantity
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setLow_quantity(Integer low_quantity) {
        this.low_quantity = low_quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.ep_ma_id
     *
     * @return the value of t_order_item.ep_ma_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getEp_ma_id() {
        return ep_ma_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.ep_ma_id
     *
     * @param ep_ma_id the value for t_order_item.ep_ma_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setEp_ma_id(Integer ep_ma_id) {
        this.ep_ma_id = ep_ma_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.audit_user_id
     *
     * @return the value of t_order_item.audit_user_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getAudit_user_id() {
        return audit_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.audit_user_id
     *
     * @param audit_user_id the value for t_order_item.audit_user_id
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setAudit_user_id(Integer audit_user_id) {
        this.audit_user_id = audit_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.audit_user_name
     *
     * @return the value of t_order_item.audit_user_name
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public String getAudit_user_name() {
        return audit_user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.audit_user_name
     *
     * @param audit_user_name the value for t_order_item.audit_user_name
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setAudit_user_name(String audit_user_name) {
        this.audit_user_name = audit_user_name == null ? null : audit_user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.update_time
     *
     * @return the value of t_order_item.update_time
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public String getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.update_time
     *
     * @param update_time the value for t_order_item.update_time
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setUpdate_time(String update_time) {
        this.update_time = update_time == null ? null : update_time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.audit_time
     *
     * @return the value of t_order_item.audit_time
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Date getAudit_time() {
        return audit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.audit_time
     *
     * @param audit_time the value for t_order_item.audit_time
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setAudit_time(Date audit_time) {
        this.audit_time = audit_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.refund_money_audit
     *
     * @return the value of t_order_item.refund_money_audit
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getRefund_money_audit() {
        return refund_money_audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.refund_money_audit
     *
     * @param refund_money_audit the value for t_order_item.refund_money_audit
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setRefund_money_audit(Integer refund_money_audit) {
        this.refund_money_audit = refund_money_audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item.refund_audit
     *
     * @return the value of t_order_item.refund_audit
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public Integer getRefund_audit() {
        return refund_audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item.refund_audit
     *
     * @param refund_audit the value for t_order_item.refund_audit
     *
     * @mbggenerated Wed Dec 07 11:02:25 CST 2016
     */
    public void setRefund_audit(Integer refund_audit) {
        this.refund_audit = refund_audit;
    }
}