package com.all580.order.entity;

import lombok.Data;

import java.io.Serializable;

@Data
public class OrderClearanceDetail implements Serializable {
    /**
     * 所属表字段为 t_order_clearance_detail.id
     */
    private Integer id;

    /**
     * 第三方流水号
     * 所属表字段为 t_order_clearance_detail.serial_no
     */
    private String serialNo;

    /**
     * 游客身份证
     * 所属表字段为 t_order_clearance_detail.sid
     */
    private String sid;

    /**
     * 手机号
     * 所属表字段为 t_order_clearance_detail.phone
     */
    private String phone;

    /**
     * 游客姓名
     * 所属表字段为 t_order_clearance_detail.name
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_clearance_detail
     *
     * @mbggenerated Mon Oct 17 10:45:26 CST 2016
     */
    private static final long serialVersionUID = 1L;

}