package com.all580.order.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class OrderClearanceSerial implements Serializable {
    /**
     * 所属表字段为 t_order_clearance_serial.id
     */
    private Integer id;

    /**
     * 第三方流水号
     * 所属表字段为 t_order_clearance_serial.serial_no
     */
    private String serial_no;

    /**
     * 子订单id
     * 所属表字段为 t_order_clearance_serial.order_item_id
     */
    private Integer order_item_id;

    /**
     * 核销数量
     * 所属表字段为 t_order_clearance_serial.quantity
     */
    private Integer quantity;

    /**
     * 哪一天的票
     * 所属表字段为 t_order_clearance_serial.day
     */
    private Date day;

    /**
     * 核销供应平台商应得金额
     * 所属表字段为 t_order_clearance_serial.supplier_money
     */
    private Integer supplier_money;

    /**
     * 通道费率
     * 所属表字段为 t_order_clearance_serial.channel_fee
     */
    private Integer channel_fee;

    /**
     * 核销时间
     * 所属表字段为 t_order_clearance_serial.clearance_time
     */
    private Date clearance_time;

    /**
     * 创建时间
     * 所属表字段为 t_order_clearance_serial.create_time
     */
    private Date create_time;

    /**
     * 所属表字段为 t_order_clearance_serial.update_time
     */
    private String update_time;

    /**
     * 是否已分账
     * 所属表字段为 t_order_clearance_serial.split
     */
    private Boolean split;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_clearance_serial
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

}