package com.all580.order.entity;

import lombok.*;

import java.io.Serializable;
import java.util.Date;

@Data
public class Order implements Serializable {
    /**
     * 所属表字段为 t_order.id
     */
    private Integer id;

    /**
     * 订单编号
     * 所属表字段为 t_order.number
     */
    private Long number;

    /**
     * 支付金额
     * 所属表字段为 t_order.pay_amount
     */
    private Integer payAmount;

    /**
     * 1-待审核
2-待支付
3-支付中
4-支付失败
5-已支付,处理中
6-已支付,交易成功
7-已取消

     * 所属表字段为 t_order.status
     */
    private Integer status;

    /**
     * 下单企业
     * 所属表字段为 t_order.buy_ep_id
     */
    private Integer buyEpId;

    /**
     * 销售员id 0表示接口下单
     * 所属表字段为 t_order.buy_operator_id
     */
    private Integer buyOperatorId;

    /**
     * 销售员姓名
     * 所属表字段为 t_order.buy_operator_name
     */
    private String buyOperatorName;

    /**
     * 创建时间
     * 所属表字段为 t_order.create_time
     */
    private Date createTime;

    /**
     * 1-余额
2-支付宝扫码
3-微信扫码
4-银联NOCARD
     * 所属表字段为 t_order.payment_type
     */
    private Integer paymentType;

    /**
     * 支付操作交易流水
     * 所属表字段为 t_order.local_payment_serial_no
     */
    private Integer localPaymentSerialNo;

    /**
     * 支付时间
     * 所属表字段为 t_order.pay_time
     */
    private Date payTime;

    /**
     * 销售金额
     * 所属表字段为 t_order.sale_amount
     */
    private Integer saleAmount;

    /**
     * 来源 0-平台下单 1-接口下单
     * 所属表字段为 t_order.from_type
     */
    private Integer fromType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    private static final long serialVersionUID = 1L;

}