package com.all580.order.entity;

import java.io.Serializable;

public class PackageOrderItemChain implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package_order_item_chain.id
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package_order_item_chain.order_item_id
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    private Integer order_item_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_package_order_item_chain.ref_item_id
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    private Integer ref_item_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_package_order_item_chain
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package_order_item_chain.id
     *
     * @return the value of t_package_order_item_chain.id
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package_order_item_chain.id
     *
     * @param id the value for t_package_order_item_chain.id
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package_order_item_chain.order_item_id
     *
     * @return the value of t_package_order_item_chain.order_item_id
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    public Integer getOrder_item_id() {
        return order_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package_order_item_chain.order_item_id
     *
     * @param order_item_id the value for t_package_order_item_chain.order_item_id
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    public void setOrder_item_id(Integer order_item_id) {
        this.order_item_id = order_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_package_order_item_chain.ref_item_id
     *
     * @return the value of t_package_order_item_chain.ref_item_id
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    public Integer getRef_item_id() {
        return ref_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_package_order_item_chain.ref_item_id
     *
     * @param ref_item_id the value for t_package_order_item_chain.ref_item_id
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    public void setRef_item_id(Integer ref_item_id) {
        this.ref_item_id = ref_item_id;
    }
}