package com.all580.order.entity;

import lombok.Data;

import java.io.Serializable;

@Data
public class PaymentJob implements Serializable {
    /**
     * 所属表字段为 t_payment_job.id
     */
    private Integer id;

    /**
     * 所属表字段为 t_payment_job.number
     */
    private Long number;

    /**
     * 380: 支付中; 381: 退款中
     * 所属表字段为 t_payment_job.type
     */
    private Integer type;

    /**
     * 当前重试次数
     * 所属表字段为 t_payment_job.retry
     */
    private Integer retry;

    /**
     * 最大重试次数
     * 所属表字段为 t_payment_job.max
     */
    private Integer max;

    /**
     * 状态
     * 所属表字段为 t_payment_job.status
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_payment_job
     *
     * @mbggenerated Wed Apr 05 10:27:48 CST 2017
     */
    private static final long serialVersionUID = 1L;

}