package com.all580.order.entity;

import java.io.Serializable;

public class RefundVisitor implements Serializable {
    /**
     * 所属表字段为 t_refund_visitor.id
     */
    private Integer id;

    /**
     * 游客ID
     * 所属表字段为 t_refund_visitor.visitor_id
     */
    private Integer visitorId;

    /**
     * 退订订单ID
     * 所属表字段为 t_refund_visitor.refund_order_id
     */
    private Integer refundOrderId;

    /**
     * 子订单ID
     * 所属表字段为 t_refund_visitor.order_item_id
     */
    private Integer orderItemId;

    /**
     * 预退订张数
     * 所属表字段为 t_refund_visitor.pre_quantity
     */
    private Integer preQuantity;

    /**
     * 实际退订张数
     * 所属表字段为 t_refund_visitor.return_quantity
     */
    private Integer returnQuantity;

    /**
     * 所属表字段为 t_refund_visitor.update_time
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_refund_visitor
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund_visitor.id
     *
     * @return the value of t_refund_visitor.id
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund_visitor.id
     *
     * @param id the value for t_refund_visitor.id
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund_visitor.visitor_id
     *
     * @return the value of t_refund_visitor.visitor_id
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public Integer getVisitorId() {
        return visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund_visitor.visitor_id
     *
     * @param visitorId the value for t_refund_visitor.visitor_id
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public void setVisitorId(Integer visitorId) {
        this.visitorId = visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund_visitor.refund_order_id
     *
     * @return the value of t_refund_visitor.refund_order_id
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public Integer getRefundOrderId() {
        return refundOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund_visitor.refund_order_id
     *
     * @param refundOrderId the value for t_refund_visitor.refund_order_id
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public void setRefundOrderId(Integer refundOrderId) {
        this.refundOrderId = refundOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund_visitor.order_item_id
     *
     * @return the value of t_refund_visitor.order_item_id
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public Integer getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund_visitor.order_item_id
     *
     * @param orderItemId the value for t_refund_visitor.order_item_id
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public void setOrderItemId(Integer orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund_visitor.pre_quantity
     *
     * @return the value of t_refund_visitor.pre_quantity
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public Integer getPreQuantity() {
        return preQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund_visitor.pre_quantity
     *
     * @param preQuantity the value for t_refund_visitor.pre_quantity
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public void setPreQuantity(Integer preQuantity) {
        this.preQuantity = preQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund_visitor.return_quantity
     *
     * @return the value of t_refund_visitor.return_quantity
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public Integer getReturnQuantity() {
        return returnQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund_visitor.return_quantity
     *
     * @param returnQuantity the value for t_refund_visitor.return_quantity
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public void setReturnQuantity(Integer returnQuantity) {
        this.returnQuantity = returnQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_refund_visitor.update_time
     *
     * @return the value of t_refund_visitor.update_time
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_refund_visitor.update_time
     *
     * @param updateTime the value for t_refund_visitor.update_time
     *
     * @mbggenerated Wed Nov 09 18:43:51 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}