package com.all580.order.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class RefundSerial implements Serializable {
    /**
     * 所属表字段为 t_refund_serial.id
     */
    private Integer id;

    /**
     * 本地交易流水
     * 所属表字段为 t_refund_serial.local_serial_no
     */
    private Long local_serial_no;

    /**
     * 第三方交易流水
     * 所属表字段为 t_refund_serial.remote_serial_no
     */
    private String remote_serial_no;

    /**
     * 数量
     * 所属表字段为 t_refund_serial.quantity
     */
    private Integer quantity;

    /**
     * json 按日期存每天退票数
     * 所属表字段为 t_refund_serial.data
     */
    private String data;

    /**
     * 退订订单id
     * 所属表字段为 t_refund_serial.refund_order_id
     */
    private Integer refund_order_id;

    /**
     * 退票时间
     * 所属表字段为 t_refund_serial.refund_time
     */
    private Date refund_time;

    /**
     * 创建时间
     * 所属表字段为 t_refund_serial.create_time
     */
    private Date create_time;

    /**
     * 所属表字段为 t_refund_serial.update_time
     */
    private String update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_refund_serial
     *
     * @mbggenerated Fri Nov 25 14:51:24 CST 2016
     */
    private static final long serialVersionUID = 1L;

}