package com.all580.order.entity;

import lombok.*;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Data
public class RefundOrder implements Serializable {
    /**
     * 所属表字段为 t_refund_order.id
     */
    private Long id;

    /**
     * 子订单id
     * 所属表字段为 t_refund_order.order_item_id
     */
    private Long orderItemId;

    /**
     * 数量
     * 所属表字段为 t_refund_order.quantity
     */
    private Integer quantity;

    /**
     * 退支付者金额
     * 所属表字段为 t_refund_order.money
     */
    private BigDecimal money;

    /**
     * 1-待审核
2-退订失败
3-退票中
4-退款中
5-退款失败
6-退订成功
     * 所属表字段为 t_refund_order.status
     */
    private Integer status;

    /**
     * json 按日期存每天退票数
     * 所属表字段为 t_refund_order.data
     */
    private String data;

    /**
     * 所属表字段为 t_refund_order.add_time
     */
    private Date addTime;

    /**
     * 退款时间
     * 所属表字段为 t_refund_order.refund_money_time
     */
    private Date refundMoneyTime;

    /**
     * 本地退款流水
     * 所属表字段为 t_refund_order.local_payment_serial_no
     */
    private Long localPaymentSerialNo;

    /**
     * 退票时间
     * 所属表字段为 t_refund_order.refund_ticket_time
     */
    private Date refundTicketTime;

    /**
     * 本地退票流水
     * 所属表字段为 t_refund_order.local_refund_serial_no
     */
    private Long localRefundSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_refund_order
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    private static final long serialVersionUID = 1L;

}