package com.all580.order.entity;

import lombok.Data;

import java.io.Serializable;

@Data
public class RefundVisitor implements Serializable {
    /**
     * 所属表字段为 t_refund_visitor.id
     */
    private Integer id;

    /**
     * 游客ID
     * 所属表字段为 t_refund_visitor.visitor_id
     */
    private Integer visitor_id;

    /**
     * 退订订单ID
     * 所属表字段为 t_refund_visitor.refund_order_id
     */
    private Integer refund_order_id;

    /**
     * 子订单ID
     * 所属表字段为 t_refund_visitor.order_item_id
     */
    private Integer order_item_id;

    /**
     * 预退订张数
     * 所属表字段为 t_refund_visitor.pre_quantity
     */
    private Integer pre_quantity;

    /**
     * 实际退订张数
     * 所属表字段为 t_refund_visitor.return_quantity
     */
    private Integer return_quantity;

    /**
     * 所属表字段为 t_refund_visitor.update_time
     */
    private String update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_refund_visitor
     *
     * @mbggenerated Fri Nov 25 14:51:24 CST 2016
     */
    private static final long serialVersionUID = 1L;

}