package com.all580.order.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class SupplierChannelBill implements Serializable {
    /**
     * 所属表字段为 t_supplier_channel_bill.id
     */
    private Integer id;

    /**
     * 供应商平台ID
     * 所属表字段为 t_supplier_channel_bill.supplier_core_ep_id
     */
    private Integer supplier_core_ep_id;

    /**
     * 所属表字段为 t_supplier_channel_bill.supplier_core_ep_name
     */
    private Integer supplier_core_ep_name;

    /**
     * 账单月份: 201607
     * 所属表字段为 t_supplier_channel_bill.bill_month
     */
    private Integer bill_month;

    /**
     * 是否已结
     * 所属表字段为 t_supplier_channel_bill.settled
     */
    private Boolean settled;

    /**
     * 账单金额
     * 所属表字段为 t_supplier_channel_bill.bill_money
     */
    private Integer bill_money;

    /**
     * 通道费
     * 所属表字段为 t_supplier_channel_bill.fee
     */
    private Integer fee;

    /**
     * 操作用户ID
     * 所属表字段为 t_supplier_channel_bill.operator_user_id
     */
    private Integer operator_user_id;

    /**
     * 操作用户名称
     * 所属表字段为 t_supplier_channel_bill.operator_user_name
     */
    private String operator_user_name;

    /**
     * 操作企业ID
     * 所属表字段为 t_supplier_channel_bill.operator_ep_id
     */
    private Integer operator_ep_id;

    /**
     * 所属表字段为 t_supplier_channel_bill.create_time
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_supplier_channel_bill
     *
     * @mbggenerated Wed Dec 14 15:26:52 CST 2016
     */
    private static final long serialVersionUID = 1L;

}