package com.all580.order.entity;

import lombok.*;

import java.io.Serializable;

@Data
public class VisitorKey implements Serializable {
    /**
     * 关联ID:子订单ID
     * 所属表字段为 t_visitor.ref_id
     */
    private Long refId;

    /**
     * 身份证号
     * 所属表字段为 t_visitor.sid
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_visitor
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    private static final long serialVersionUID = 1L;

}