package com.all580.payment.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Capital implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital.ep_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer epId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital.credit
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital.balance
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital.can_cash
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer canCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital.core_ep_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer coreEpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital.id
     *
     * @return the value of t_capital.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital.id
     *
     * @param id the value for t_capital.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital.ep_id
     *
     * @return the value of t_capital.ep_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getEpId() {
        return epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital.ep_id
     *
     * @param epId the value for t_capital.ep_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setEpId(Integer epId) {
        this.epId = epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital.credit
     *
     * @return the value of t_capital.credit
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital.credit
     *
     * @param credit the value for t_capital.credit
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital.balance
     *
     * @return the value of t_capital.balance
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital.balance
     *
     * @param balance the value for t_capital.balance
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital.can_cash
     *
     * @return the value of t_capital.can_cash
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getCanCash() {
        return canCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital.can_cash
     *
     * @param canCash the value for t_capital.can_cash
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setCanCash(Integer canCash) {
        this.canCash = canCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital.core_ep_id
     *
     * @return the value of t_capital.core_ep_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getCoreEpId() {
        return coreEpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital.core_ep_id
     *
     * @param coreEpId the value for t_capital.core_ep_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setCoreEpId(Integer coreEpId) {
        this.coreEpId = coreEpId;
    }
}