package com.all580.payment.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class CapitalSerial implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_serial.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_serial.ref_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private String refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_serial.ref_type
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer refType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_serial.capital_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer capitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_serial.old_balance
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer oldBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_serial.old_can_cash
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer oldCanCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_serial.new_balance
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer newBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_serial.new_can_cash
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer newCanCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_capital_serial.create_time
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_capital_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_serial.id
     *
     * @return the value of t_capital_serial.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_serial.id
     *
     * @param id the value for t_capital_serial.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_serial.ref_id
     *
     * @return the value of t_capital_serial.ref_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public String getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_serial.ref_id
     *
     * @param refId the value for t_capital_serial.ref_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setRefId(String refId) {
        this.refId = refId == null ? null : refId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_serial.ref_type
     *
     * @return the value of t_capital_serial.ref_type
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getRefType() {
        return refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_serial.ref_type
     *
     * @param refType the value for t_capital_serial.ref_type
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setRefType(Integer refType) {
        this.refType = refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_serial.capital_id
     *
     * @return the value of t_capital_serial.capital_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getCapitalId() {
        return capitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_serial.capital_id
     *
     * @param capitalId the value for t_capital_serial.capital_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setCapitalId(Integer capitalId) {
        this.capitalId = capitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_serial.old_balance
     *
     * @return the value of t_capital_serial.old_balance
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getOldBalance() {
        return oldBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_serial.old_balance
     *
     * @param oldBalance the value for t_capital_serial.old_balance
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setOldBalance(Integer oldBalance) {
        this.oldBalance = oldBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_serial.old_can_cash
     *
     * @return the value of t_capital_serial.old_can_cash
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getOldCanCash() {
        return oldCanCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_serial.old_can_cash
     *
     * @param oldCanCash the value for t_capital_serial.old_can_cash
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setOldCanCash(Integer oldCanCash) {
        this.oldCanCash = oldCanCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_serial.new_balance
     *
     * @return the value of t_capital_serial.new_balance
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getNewBalance() {
        return newBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_serial.new_balance
     *
     * @param newBalance the value for t_capital_serial.new_balance
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setNewBalance(Integer newBalance) {
        this.newBalance = newBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_serial.new_can_cash
     *
     * @return the value of t_capital_serial.new_can_cash
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getNewCanCash() {
        return newCanCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_serial.new_can_cash
     *
     * @param newCanCash the value for t_capital_serial.new_can_cash
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setNewCanCash(Integer newCanCash) {
        this.newCanCash = newCanCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_capital_serial.create_time
     *
     * @return the value of t_capital_serial.create_time
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_capital_serial.create_time
     *
     * @param createTime the value for t_capital_serial.create_time
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}