package com.all580.payment.entity;

import java.io.Serializable;

public class PaymentReq implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_req.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_req.ord_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Long ordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_req.serial_no
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Long serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_req.data
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_payment_req
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_req.id
     *
     * @return the value of t_payment_req.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_req.id
     *
     * @param id the value for t_payment_req.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_req.ord_id
     *
     * @return the value of t_payment_req.ord_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Long getOrdId() {
        return ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_req.ord_id
     *
     * @param ordId the value for t_payment_req.ord_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setOrdId(Long ordId) {
        this.ordId = ordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_req.serial_no
     *
     * @return the value of t_payment_req.serial_no
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Long getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_req.serial_no
     *
     * @param serialNo the value for t_payment_req.serial_no
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_req.data
     *
     * @return the value of t_payment_req.data
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_req.data
     *
     * @param data the value for t_payment_req.data
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}