package com.all580.payment.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PaymentSerial implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_serial.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_serial.local_serial_no
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Long localSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_serial.remote_serial_no
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private String remoteSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_serial.pay_amount
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private BigDecimal payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_serial.pay_time
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private String payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_serial.ref_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Long refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_serial.ref_type
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer refType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_serial.payment_type
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Integer paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_serial.create_time
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_payment_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_serial.id
     *
     * @return the value of t_payment_serial.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_serial.id
     *
     * @param id the value for t_payment_serial.id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_serial.local_serial_no
     *
     * @return the value of t_payment_serial.local_serial_no
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Long getLocalSerialNo() {
        return localSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_serial.local_serial_no
     *
     * @param localSerialNo the value for t_payment_serial.local_serial_no
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setLocalSerialNo(Long localSerialNo) {
        this.localSerialNo = localSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_serial.remote_serial_no
     *
     * @return the value of t_payment_serial.remote_serial_no
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public String getRemoteSerialNo() {
        return remoteSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_serial.remote_serial_no
     *
     * @param remoteSerialNo the value for t_payment_serial.remote_serial_no
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setRemoteSerialNo(String remoteSerialNo) {
        this.remoteSerialNo = remoteSerialNo == null ? null : remoteSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_serial.pay_amount
     *
     * @return the value of t_payment_serial.pay_amount
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_serial.pay_amount
     *
     * @param payAmount the value for t_payment_serial.pay_amount
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_serial.pay_time
     *
     * @return the value of t_payment_serial.pay_time
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public String getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_serial.pay_time
     *
     * @param payTime the value for t_payment_serial.pay_time
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setPayTime(String payTime) {
        this.payTime = payTime == null ? null : payTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_serial.ref_id
     *
     * @return the value of t_payment_serial.ref_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Long getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_serial.ref_id
     *
     * @param refId the value for t_payment_serial.ref_id
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setRefId(Long refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_serial.ref_type
     *
     * @return the value of t_payment_serial.ref_type
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getRefType() {
        return refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_serial.ref_type
     *
     * @param refType the value for t_payment_serial.ref_type
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setRefType(Integer refType) {
        this.refType = refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_serial.payment_type
     *
     * @return the value of t_payment_serial.payment_type
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_serial.payment_type
     *
     * @param paymentType the value for t_payment_serial.payment_type
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_serial.create_time
     *
     * @return the value of t_payment_serial.create_time
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_serial.create_time
     *
     * @param createTime the value for t_payment_serial.create_time
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}