package com.all580.ep.dao;

import com.all580.ep.entity.EpPush;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EpPushMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_push
     *
     * @mbggenerated Thu Apr 06 09:05:22 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_push
     *
     * @mbggenerated Thu Apr 06 09:05:22 CST 2017
     */
    int insert(EpPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_push
     *
     * @mbggenerated Thu Apr 06 09:05:22 CST 2017
     */
    int insertSelective(EpPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_push
     *
     * @mbggenerated Thu Apr 06 09:05:22 CST 2017
     */
    EpPush selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_push
     *
     * @mbggenerated Thu Apr 06 09:05:22 CST 2017
     */
    int updateByPrimaryKeySelective(EpPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_push
     *
     * @mbggenerated Thu Apr 06 09:05:22 CST 2017
     */
    int updateByPrimaryKey(EpPush record);

    List<EpPush> selectByEpId(@Param("epId") String epId);
}