package com.all580.ep.dao;

import com.all580.ep.entity.EpSendVoucher;
import org.apache.ibatis.annotations.Param;

public interface EpSendVoucherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_send_voucher
     *
     * @mbggenerated Mon Jun 26 10:34:50 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_send_voucher
     *
     * @mbggenerated Mon Jun 26 10:34:50 CST 2017
     */
    int insert(EpSendVoucher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_send_voucher
     *
     * @mbggenerated Mon Jun 26 10:34:50 CST 2017
     */
    int insertSelective(EpSendVoucher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_send_voucher
     *
     * @mbggenerated Mon Jun 26 10:34:50 CST 2017
     */
    EpSendVoucher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_send_voucher
     *
     * @mbggenerated Mon Jun 26 10:34:50 CST 2017
     */
    int updateByPrimaryKeySelective(EpSendVoucher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ep_send_voucher
     *
     * @mbggenerated Mon Jun 26 10:34:50 CST 2017
     */
    int updateByPrimaryKey(EpSendVoucher record);

    EpSendVoucher selectByEp(@Param("epId") int epId, @Param("coreEpId") int coreEpId);
}