package com.all580.ep.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class EpPush implements Serializable {
    /**
     * 所属表字段为 t_ep_push.id
     */
    private Integer id;

    /**
     * 企业ID
     * 所属表字段为 t_ep_push.ep_id
     */
    private String ep_id;

    /**
     * 企业名称 
     * 所属表字段为 t_ep_push.ep_name
     */
    private String ep_name;

    /**
     * 推送地址
     * 所属表字段为 t_ep_push.url
     */
    private String url;

    /**
     * 类型
     * 所属表字段为 t_ep_push.type
     */
    private String type;

    /**
     * 所属表字段为 t_ep_push.create_time
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ep_push
     *
     * @mbggenerated Thu Apr 06 09:05:22 CST 2017
     */
    private static final long serialVersionUID = 1L;

}