package com.all580.ep.entity;

import lombok.Data;

import java.io.Serializable;

@Data
public class EpSendVoucher implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ep_send_voucher.id
     *
     * @mbggenerated Mon Jun 26 10:34:50 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ep_send_voucher.ep_id
     *
     * @mbggenerated Mon Jun 26 10:34:50 CST 2017
     */
    private Integer ep_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ep_send_voucher.core_ep_id
     *
     * @mbggenerated Mon Jun 26 10:34:50 CST 2017
     */
    private Integer core_ep_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ep_send_voucher.send_voucher
     *
     * @mbggenerated Mon Jun 26 10:34:50 CST 2017
     */
    private Boolean send_voucher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ep_send_voucher
     *
     * @mbggenerated Mon Jun 26 10:34:50 CST 2017
     */
    private static final long serialVersionUID = 1L;

}