package com.all580.payment.dao;

import com.all580.payment.entity.CapitalSerial;

import java.util.List;

public interface CapitalSerialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int insert(CapitalSerial record);
    int insertBatch(List<CapitalSerial> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int insertSelective(CapitalSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    CapitalSerial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int updateByPrimaryKeySelective(CapitalSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int updateByPrimaryKey(CapitalSerial record);
}