package com.all580.payment.dao;

import com.all580.payment.api.model.BalanceChangeInfo;
import com.all580.payment.entity.Capital;

import java.util.List;

public interface CapitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int insert(Capital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int insertSelective(Capital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    Capital selectByPrimaryKey(Integer id);
    List<Capital> selectForUpdateByEpList(List<BalanceChangeInfo> changeInfos);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int updateByPrimaryKeySelective(Capital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_capital
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int updateByPrimaryKey(Capital record);

    int batchUpdateById(List<Capital> capitalList);
}