package com.all580.payment.dao;

import com.all580.payment.entity.PaymentReq;

public interface PaymentReqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_req
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_req
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int insert(PaymentReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_req
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int insertSelective(PaymentReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_req
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    PaymentReq selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_req
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int updateByPrimaryKeySelective(PaymentReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_req
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int updateByPrimaryKey(PaymentReq record);
}