package com.all580.payment.dao;

import com.all580.payment.entity.PaymentSerial;

public interface PaymentSerialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int insert(PaymentSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int insertSelective(PaymentSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    PaymentSerial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int updateByPrimaryKeySelective(PaymentSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_serial
     *
     * @mbggenerated Fri Sep 30 14:48:06 CST 2016
     */
    int updateByPrimaryKey(PaymentSerial record);
}