package com.all580.order.dao;

import com.all580.order.entity.ChannelBill;

public interface ChannelBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_bill
     *
     * @mbggenerated Tue Dec 13 14:50:14 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_bill
     *
     * @mbggenerated Tue Dec 13 14:50:14 CST 2016
     */
    int insert(ChannelBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_bill
     *
     * @mbggenerated Tue Dec 13 14:50:14 CST 2016
     */
    int insertSelective(ChannelBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_bill
     *
     * @mbggenerated Tue Dec 13 14:50:14 CST 2016
     */
    ChannelBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_bill
     *
     * @mbggenerated Tue Dec 13 14:50:14 CST 2016
     */
    int updateByPrimaryKeySelective(ChannelBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_bill
     *
     * @mbggenerated Tue Dec 13 14:50:14 CST 2016
     */
    int updateByPrimaryKey(ChannelBill record);
}