package com.all580.order.dao;

import com.all580.order.entity.ClearanceWashedSerial;

public interface ClearanceWashedSerialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    int insert(ClearanceWashedSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    int insertSelective(ClearanceWashedSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    ClearanceWashedSerial selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    int updateByPrimaryKeySelective(ClearanceWashedSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    int updateByPrimaryKey(ClearanceWashedSerial record);
}