package com.all580.order.dao;

import com.all580.order.entity.ClearanceWashedSerial;

public interface ClearanceWashedSerialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    int insert(ClearanceWashedSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    int insertSelective(ClearanceWashedSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    ClearanceWashedSerial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    int updateByPrimaryKeySelective(ClearanceWashedSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clearance_washed_serial
     *
     * @mbggenerated Thu Feb 09 14:03:33 CST 2017
     */
    int updateByPrimaryKey(ClearanceWashedSerial record);

    /**
     * 根据流水号获取冲正流水
     * @param sn
     * @return
     */
    ClearanceWashedSerial selectBySn(String sn);
}