package com.all580.order.dao;

import com.all580.order.entity.GroupMember;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface GroupMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_member
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_member
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    int insert(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_member
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    int insertSelective(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_member
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    GroupMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_member
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    int updateByPrimaryKeySelective(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_member
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    int updateByPrimaryKey(GroupMember record);

    /**
     * 根据团队获取团队成员
     * @param groupId 团队ID
     * @return
     */
    List<GroupMember> selectByGroup(@Param("groupId") Integer groupId, @Param("lastId") Integer lastId);

    /**
     * 根据团队获取团队成员ID
     * @param groupId 团队ID
     * @return
     */
    Set<Integer> selectIdsByGroup(@Param("groupId") Integer groupId);

    /**
     * 根据团队删除该团队所有成员
     * @param groupId 团队ID
     * @return
     */
    int deleteByGroup(@Param("groupId") Integer groupId);
}