package com.all580.order.dao;

import com.all580.order.entity.Group;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    Group selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu Dec 01 11:25:59 CST 2016
     */
    int updateByPrimaryKey(Group record);

    /**
     * 统计团队数量
     * @param number 团号
     * @param guide_name 导游姓名
     * @param start 出团开始时间
     * @param end 出团结束时间
     * @param province 省
     * @param city 市
     * @return
     */
    int countGroupList(@Param("ep_id") Integer ep_id,@Param("number") String number, @Param("guide_name") String guide_name, @Param("start") String start, @Param("end") String end, @Param("province") String province, @Param("city") String city);

    /**
     * 查询团队列表
     * @param number 团号
     * @param guide_name 导游姓名
     * @param start 出团开始时间
     * @param end 出团结束时间
     * @param province 省
     * @param city 市
     * @return
     */
    List<Map> queryGroupList(@Param("ep_id") Integer ep_id,@Param("number") String number, @Param("guide_name") String guide_name, @Param("start") String start, @Param("end") String end, @Param("province") String province, @Param("city") String city, @Param("record_start") Integer record_start ,@Param("record_count") Integer record_count);

    Map queryGroupById(@Param("id") Integer id);
}