package com.all580.order.dao;

import com.all580.order.entity.MaSendResponse;
import java.util.List;

public interface MaSendResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ma_send_response
     *
     * @mbggenerated Thu Oct 13 15:52:53 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ma_send_response
     *
     * @mbggenerated Thu Oct 13 15:52:53 CST 2016
     */
    int insert(MaSendResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ma_send_response
     *
     * @mbggenerated Thu Oct 13 15:52:53 CST 2016
     */
    MaSendResponse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ma_send_response
     *
     * @mbggenerated Thu Oct 13 15:52:53 CST 2016
     */
    List<MaSendResponse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ma_send_response
     *
     * @mbggenerated Thu Oct 13 15:52:53 CST 2016
     */
    int updateByPrimaryKey(MaSendResponse record);

    /**
     * 根据子订单ID获取凭证列表
     * @param itemId 子订单ID
     * @return
     */
    List<MaSendResponse> selectByOrderItemId(Integer itemId);
}