package com.all580.order.dao;

import com.all580.order.entity.OrderClearanceDetail;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderClearanceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_detail
     *
     * @mbggenerated Fri Nov 25 14:51:24 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_detail
     *
     * @mbggenerated Fri Nov 25 14:51:24 CST 2016
     */
    int insert(OrderClearanceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_detail
     *
     * @mbggenerated Fri Nov 25 14:51:24 CST 2016
     */
    int insertSelective(OrderClearanceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_detail
     *
     * @mbggenerated Fri Nov 25 14:51:24 CST 2016
     */
    OrderClearanceDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_detail
     *
     * @mbggenerated Fri Nov 25 14:51:24 CST 2016
     */
    int updateByPrimaryKeySelective(OrderClearanceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_detail
     *
     * @mbggenerated Fri Nov 25 14:51:24 CST 2016
     */
    int updateByPrimaryKey(OrderClearanceDetail record);

    /**
     * 根据验票流水获取核销明细
     * @param sn 验票流水
     * @return
     */
    OrderClearanceDetail selectBySn(@Param("sn") String sn);
    List<OrderClearanceDetail> selectItemClearanceDetail(Integer itemId);
}