package com.all580.order.dao;

import com.all580.order.entity.OrderItemDetail;
import java.util.List;

public interface OrderItemDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_detail
     *
     * @mbggenerated Sun Oct 09 11:42:35 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_detail
     *
     * @mbggenerated Sun Oct 09 11:42:35 CST 2016
     */
    int insert(OrderItemDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_detail
     *
     * @mbggenerated Sun Oct 09 11:42:35 CST 2016
     */
    OrderItemDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_detail
     *
     * @mbggenerated Sun Oct 09 11:42:35 CST 2016
     */
    List<OrderItemDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_detail
     *
     * @mbggenerated Sun Oct 09 11:42:35 CST 2016
     */
    int updateByPrimaryKey(OrderItemDetail record);
}