package com.all580.order.dao;

import com.all580.order.entity.Order;
import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int updateByPrimaryKey(Order record);

    /**
     * 根据订单编号(流水)获取订单
     * @param sn 编号(流水)
     * @return
     */
    Order selectBySN(Long sn);
}