package com.all580.order.dao;

import com.all580.order.entity.OrderClearanceSerial;

public interface OrderClearanceSerialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    int insert(OrderClearanceSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    int insertSelective(OrderClearanceSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    OrderClearanceSerial selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    int updateByPrimaryKeySelective(OrderClearanceSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_clearance_serial
     *
     * @mbggenerated Tue Sep 27 17:38:35 CST 2016
     */
    int updateByPrimaryKey(OrderClearanceSerial record);
}