package com.all580.order.dao;

import com.all580.order.entity.OrderItemAccount;
import java.util.List;

public interface OrderItemAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_account
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_account
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    int insert(OrderItemAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_account
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    OrderItemAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_account
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    List<OrderItemAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_account
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    int updateByPrimaryKey(OrderItemAccount record);
}