package com.all580.order.dao;

import com.all580.order.entity.PackageOrderChain;

public interface PackageOrderChainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    int insert(PackageOrderChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    int insertSelective(PackageOrderChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    PackageOrderChain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    int updateByPrimaryKeySelective(PackageOrderChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    int updateByPrimaryKey(PackageOrderChain record);
}