package com.all580.order.dao;

import com.all580.order.entity.packageOrderChain;

public interface packageOrderChainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    int insert(packageOrderChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    int insertSelective(packageOrderChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    packageOrderChain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    int updateByPrimaryKeySelective(packageOrderChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_chain
     *
     * @mbggenerated Thu Aug 17 09:41:03 CST 2017
     */
    int updateByPrimaryKey(packageOrderChain record);
}