package com.all580.order.dao;

import com.all580.order.entity.PackageOrderItemChain;

public interface PackageOrderItemChainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_item_chain
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_item_chain
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    int insert(PackageOrderItemChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_item_chain
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    int insertSelective(PackageOrderItemChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_item_chain
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    PackageOrderItemChain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_item_chain
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    int updateByPrimaryKeySelective(PackageOrderItemChain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_package_order_item_chain
     *
     * @mbggenerated Fri Aug 18 17:47:04 CST 2017
     */
    int updateByPrimaryKey(PackageOrderItemChain record);
}