package com.all580.order.dao;

import com.all580.order.entity.PaymentJob;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaymentJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_job
     *
     * @mbggenerated Wed Apr 05 10:27:48 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_job
     *
     * @mbggenerated Wed Apr 05 10:27:48 CST 2017
     */
    int insert(PaymentJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_job
     *
     * @mbggenerated Wed Apr 05 10:27:48 CST 2017
     */
    int insertSelective(PaymentJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_job
     *
     * @mbggenerated Wed Apr 05 10:27:48 CST 2017
     */
    PaymentJob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_job
     *
     * @mbggenerated Wed Apr 05 10:27:48 CST 2017
     */
    int updateByPrimaryKeySelective(PaymentJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_job
     *
     * @mbggenerated Wed Apr 05 10:27:48 CST 2017
     */
    int updateByPrimaryKey(PaymentJob record);

    /**
     * 重试
     * @param number
     * @param type
     * @return
     */
    int retry(@Param("number") Long number, @Param("type") Integer type);

    int disable(@Param("number") Long number, @Param("type") Integer type);

    PaymentJob selectByNumberAndType(@Param("number") Long number, @Param("type") Integer type);
}