package com.all580.order.dao;

import com.all580.order.entity.RefundOrder;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RefundOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_order
     *
     * @mbggenerated Wed Feb 15 09:51:21 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_order
     *
     * @mbggenerated Wed Feb 15 09:51:21 CST 2017
     */
    int insert(RefundOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_order
     *
     * @mbggenerated Wed Feb 15 09:51:21 CST 2017
     */
    int insertSelective(RefundOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_order
     *
     * @mbggenerated Wed Feb 15 09:51:21 CST 2017
     */
    RefundOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_order
     *
     * @mbggenerated Wed Feb 15 09:51:21 CST 2017
     */
    int updateByPrimaryKeySelective(RefundOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_order
     *
     * @mbggenerated Wed Feb 15 09:51:21 CST 2017
     */
    int updateByPrimaryKey(RefundOrder record);

    /**
     * 根据退订流水编号获取退订订单
     * @param sn 编号
     * @return
     */
    RefundOrder selectBySN(Long sn);

    /**
     * 根据子订单ID以及退票本地流水查询退票订单
     * @param itemId 子订单ID
     * @param refundSn 本地退票流水
     * @return
     */
    RefundOrder selectByItemIdAndRefundSn(@Param("itemId") Integer itemId, @Param("refundSn") Long refundSn);

    /**
     * 根据子订单ID以及退票游客ID查询退票订单
     * @param itemId
     * @param visitorId
     * @return
     */
    RefundOrder selectByItemIdAndVisitor(@Param("itemId") Integer itemId, @Param("visitorId") Integer visitorId);

    /**
     * 根据子订单ID获取退订订单
     * @param itemId
     * @return
     */
    List<RefundOrder> selectByItemId(@Param("itemId") Integer itemId);


    /**
     * isTrue  =1  状态就等于状态  isTrue=2  状态就不等于状态
     * @param itemId
     * @param status
     * @param isTrue
     * @return
     */
    int  selectByItemIdAndStatus(@Param("itemId") Integer itemId,@Param("status") Integer status,@Param("isTrue") Integer isTrue);

    /**
     * 获取子订单退票总数
     * @param order_item_id
     * @return
     */
    int selectItemQuantity(@Param("order_item_id") Integer order_item_id);

    /**
     * 查询退款中的退订订单
     * @return
     */
    List<RefundOrder> selectRefundMoneyOrder();
}