package com.all580.order.dao;

import com.all580.order.entity.RefundAccount;
import java.util.List;

public interface RefundAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_account
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_account
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int insert(RefundAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_account
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    RefundAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_account
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    List<RefundAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_account
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int updateByPrimaryKey(RefundAccount record);
}