package com.all580.order.dao;

import com.all580.order.entity.RefundOrder;
import java.util.List;

public interface RefundOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_order
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_order
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    int insert(RefundOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_order
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    RefundOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_order
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    List<RefundOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_refund_order
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    int updateByPrimaryKey(RefundOrder record);
}