package com.all580.order.dao;

import com.all580.order.entity.Shipping;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated Mon Oct 24 14:36:57 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated Mon Oct 24 14:36:57 CST 2016
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated Mon Oct 24 14:36:57 CST 2016
     */
    int insertSelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated Mon Oct 24 14:36:57 CST 2016
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated Mon Oct 24 14:36:57 CST 2016
     */
    int updateByPrimaryKeySelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated Mon Oct 24 14:36:57 CST 2016
     */
    int updateByPrimaryKey(Shipping record);
}