package com.all580.order.dao;

import com.all580.order.entity.Shipping;
import java.util.List;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    List<Shipping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shipping
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int updateByPrimaryKey(Shipping record);
}