package com.all580.order.dao;

import com.all580.order.entity.Visitor;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    int deleteByPrimaryKey(@Param("refId") Integer refId, @Param("sid") String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    int insert(Visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    Visitor selectByPrimaryKey(@Param("refId") Integer refId, @Param("sid") String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    List<Visitor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Thu Sep 29 13:58:49 CST 2016
     */
    int updateByPrimaryKey(Visitor record);
}