package com.all580.order.dao;

import com.all580.order.entity.Visitor;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int deleteByPrimaryKey(@Param("refId") Integer refId, @Param("sid") String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int insert(Visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    Visitor selectByPrimaryKey(@Param("refId") Integer refId, @Param("sid") String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    List<Visitor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visitor
     *
     * @mbggenerated Fri Sep 30 15:22:08 CST 2016
     */
    int updateByPrimaryKey(Visitor record);

    /**
     * 根据子产品和身份证获取该身份证在指定时间内订购张数
     * @param productSubId 子产品ID
     * @param sid 身份证
     * @param start 开始时间
     * @param end 结束时间
     * @return
     */
    int quantityBySidAndProductForDate(@Param("productSubId") Integer productSubId, @Param("sid") String sid,
                                       @Param("start") Date start, @Param("end") Date end);
}